# Generated by Django 2.1.3 on 2018-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_pdu_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pdu_created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
