# Generated by Django 2.1.3 on 2018-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181124_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_name', models.CharField(max_length=200)),
                ('pdu_img_name', models.CharField(max_length=200)),
                ('pdu_img_url', models.FileField(upload_to='uploads/tourimages/')),
                ('main_img', models.BooleanField(null=True)),
            ],
        ),
    ]
