# Generated by Django 2.1.3 on 2018-12-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='pdu_uid',
            field=models.IntegerField(default=0),
        ),
    ]
