# Generated by Django 2.1.3 on 2018-12-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181204_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='pdu_img_url',
            field=models.URLField(),
        ),
    ]
