# Generated by Django 2.1.3 on 2018-12-05 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181204_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdu_created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
