# Generated by Django 2.1.3 on 2018-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181209_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city_img_bar', models.URLField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='pdu_img_url',
            field=models.URLField(max_length=600),
        ),
    ]
