# Generated by Django 2.1.3 on 2018-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181209_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('kakaoid', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=600)),
                ('introself', models.TextField(blank=True, null=True)),
                ('video', models.URLField(max_length=600)),
                ('gender', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=600)),
                ('language', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('major', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('cellnumber', models.CharField(max_length=200)),
                ('emergency', models.CharField(max_length=200)),
                ('afilliation', models.CharField(max_length=200)),
                ('visited_country', models.CharField(max_length=200)),
                ('next_contry', models.CharField(max_length=200)),
            ],
        ),
    ]
