# Generated by Django 2.1.3 on 2018-12-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='next_contry',
            new_name='next_country',
        ),
    ]
