# Generated by Django 2.1.3 on 2018-12-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181212_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='video',
        ),
        migrations.AddField(
            model_name='profile',
            name='videoId',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
