# Generated by Django 2.1.3 on 2018-12-12 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181212_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_image_bar_name',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='city_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='city_video_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
