# Generated by Django 2.1.3 on 2018-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
