# Generated by Django 2.1.3 on 2018-12-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='createdDate',
            new_name='lastUpdated',
        ),
    ]
