# Generated by Django 2.1.3 on 2018-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181214_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
