# Generated by Django 2.1.3 on 2018-12-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_travel_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
