# Generated by Django 2.1.3 on 2018-12-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lastUpdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
