# Generated by Django 2.1.3 on 2018-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181214_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=600)),
                ('area', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('lastUpdated', models.DateField(blank=True, null=True)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
