# Generated by Django 2.1.3 on 2018-12-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_localcommunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localcommunity',
            old_name='name',
            new_name='title',
        ),
    ]
