# Generated by Django 2.1.3 on 2018-12-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181214_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booker',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
