# Generated by Django 2.1.3 on 2018-12-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20181215_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lastUpdate',
            new_name='lastUpdated',
        ),
    ]
