# Generated by Django 2.1.3 on 2018-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20181218_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('lastUpdated', models.DateTimeField(blank=True)),
                ('articleId', models.IntegerField(default=0)),
                ('parentId', models.IntegerField(default=0)),
            ],
        ),
    ]
