# Generated by Django 2.1.3 on 2018-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_localcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdu_meeting_point_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pdu_meeting_point_lng',
            field=models.IntegerField(default=0),
        ),
    ]
