# Generated by Django 2.1.3 on 2018-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20181230_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdu_meeting_point_lat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdu_meeting_point_lng',
            field=models.CharField(max_length=200),
        ),
    ]
