# Generated by Django 2.1.3 on 2019-01-06 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181230_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdu_duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pdu_meeting_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
