# Generated by Django 2.1.3 on 2019-01-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190106_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('socialId', models.CharField(max_length=200)),
                ('socialName', models.CharField(max_length=200)),
                ('joinTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
