# Generated by Django 2.1.3 on 2019-01-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_socialuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='period',
        ),
        migrations.AddField(
            model_name='event',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
