# Generated by Django 2.1.3 on 2019-01-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190114_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='videoId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
