# Generated by Django 2.1.3 on 2019-01-16 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190116_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='starttime',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
